name: starters

services:
  app-nestjs-typeorm-postgre:
    build:
      context: ./apps/nestjs-typeorm-postgre
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    env_file:
      - ./apps/nestjs-typeorm-postgre/.env.production
    volumes:
      - ./apps/nestjs-typeorm-postgre/logs:/usr/src/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  seaweedfs-master:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-master
    command: master -ip.bind=0.0.0.0 -port=${SEAWEEDFS_MASTER_PORT}
    volumes:
      - seaweedfs-master-data:/data
    restart: unless-stopped

  seaweedfs-volume:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-volume
    command: volume -mserver=seaweedfs-master:${SEAWEEDFS_MASTER_PORT} -port=${SEAWEEDFS_VOLUME_PORT} -ip.bind=0.0.0.0
    volumes:
      - seaweedfs-volume-data:/data
    depends_on:
      - seaweedfs-master
    restart: unless-stopped

  seaweedfs-filer:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-filer
    command: filer -master=seaweedfs-master:${SEAWEEDFS_MASTER_PORT} -port=${SEAWEEDFS_FILER_PORT} -ip.bind=0.0.0.0
    volumes:
      - seaweedfs-filer-data:/data
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
    restart: unless-stopped

  seaweedfs-s3:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-s3
    command: s3 -filer=seaweedfs-filer:${SEAWEEDFS_FILER_PORT} -port=${SEAWEEDFS_S3_PORT} -ip.bind=0.0.0.0 -config=/etc/seaweedfs/s3-config.json
    volumes:
      - ./seaweedfs/s3-config.json:/etc/seaweedfs/s3-config.json
    depends_on:
      - seaweedfs-filer
    restart: unless-stopped
    expose:
      - ${SEAWEEDFS_S3_PORT}

  seaweedfs-admin:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-admin
    command: 'admin -masters="seaweedfs-master:${SEAWEEDFS_MASTER_PORT}" -port=${SEAWEEDFS_ADMIN_PORT} -adminUser=${SEAWEEDFS_ADMIN_USER} -adminPassword=${SEAWEEDFS_ADMIN_PASSWORD} -dataDir=/data'
    volumes:
      - seaweedfs-admin-data:/data
    depends_on:
      - seaweedfs-master
    restart: unless-stopped
    expose:
      - :${SEAWEEDFS_ADMIN_PORT}

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=${N8N_SUBDOMAIN}.${N8N_DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PATH=${N8N_PATH}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=production
      - WEBHOOK_URL=${N8N_PROTOCOL}://${N8N_SUBDOMAIN}.${N8N_DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${N8N_GENERIC_TIMEZONE}
      - TZ=${N8N_GENERIC_TIMEZONE}
      - N8N_RESTRICT_FILE_ACCESS_TO=/files
    volumes:
      - n8n-data:/home/node/.n8n
      - ./n8n/local-files:/files
    expose:
      - '5678'

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"

  redis:
    image: redis:7-alpine
    ports:
      - '6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_ADMIN_ALLOWED_HOSTS: ${POSTGRES_ADMIN_ALLOWED_HOSTS}
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root']
      interval: 5s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_ADMIN_ALLOWED_HOSTS: ${MYSQL_ADMIN_ALLOWED_HOSTS}
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  seaweedfs-master-data:
  seaweedfs-volume-data:
  seaweedfs-filer-data:
  seaweedfs-admin-data:
  n8n-data:
  certbot-etc:
  certbot-www:
  redis-data:
  postgres-data:
  mysql-data:

