name: starters

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=${N8N_SUBDOMAIN}.${N8N_DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PATH=${N8N_PATH}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=production
      - WEBHOOK_URL=${N8N_PROTOCOL}://${N8N_SUBDOMAIN}.${N8N_DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${N8N_GENERIC_TIMEZONE}
      - TZ=${N8N_GENERIC_TIMEZONE}
      - N8N_RESTRICT_FILE_ACCESS_TO=/files
    volumes:
      - n8n-data:/home/node/.n8n
      - ./n8n/local-files:/files
    expose:
      - '5678'

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"

  redis:
    image: redis:7-alpine
    ports:
      - '6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_ADMIN_ALLOWED_HOSTS: ${POSTGRES_ADMIN_ALLOWED_HOSTS}
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_ADMIN_ALLOWED_HOSTS: ${MYSQL_ADMIN_ALLOWED_HOSTS}
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  n8n-data:
  certbot-etc:
  certbot-www:
  redis-data:
  postgres-data:
  mysql-data:

